packages:
  - functions
  - functions/shared

minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - '@ugrc/*'
  - uuid@11.1.1
  - '@opentelemetry/core@2.8.0'
  - ts-deepmerge@8.0.0
  - nanoid@3.3.18

allowBuilds:
  '@firebase/util': true
  '@swc/core': true
  '@vaadin/vaadin-usage-statistics': true
  core-js: true
  esbuild: true
  protobufjs: true
  re2: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@firebase/util'
  - esbuild
  - protobufjs
